### ISSUE TITLE
Discussion: Roadmap for future components.

### ISSUE THREAD

**Issue by sankhadeeproy007** [GeekyAnts/NativeBase#38]
We were thinking about the future direction of NativeBase as a whole and after some feedback from users in reddit, facebook, quora and the likes.
One point which divided opinions vastly was the look and feel of the components in NativeBase. There are specific guidelines laid down by both Google and Apple as to how the native apps should actually look and as of now, NativeBase isn't really adhering to those guidelines. So your input would be appreciated in these following UI components
1> The`Navbar` component
2> `Buttons` with/without ripple effect
3> TabBarIos and similar implementation in Android
4>  DatePicker component
5> Picker/Dropdown component
6> Floating action button
7> Floating Labels
Add more components if you feel is missing from the list.

**Comment by steida** [comment]
I think it should be up to the styles / themes. The Ripple effect is just eye candy IMHO. For those who want it, I would recommend the whole material lib.

**Comment by JagdishUpadhyay** [comment]
I agree with @steida. Floating labels are missing in input boxes

**Comment by sntran** [comment]
Can I add "Floating Action Button" to the list of missing components?

**Comment by perusal** [comment]
@steida @JagdishUpadhyay @sntran Those are all cool suggestions. We've added them to our Roadmap. :)

**Comment by yaronlevi** [comment]
I think the main focus should be on a decent nice looking calendar picker. It is a very basic component, and is currently missing from the whole react native eco system.

**Comment by hfogelberg** [comment]
Do you have an estimate for when the calendar picker might be ready?

**Comment by allentv** [comment]
Here is a list of components that would make easier - https://ionicframework.com/docs/v2/components/#overview

**Comment by rodperottoni** [comment]
Allowing users to choose between **TouchableOpacity/TouchableNativeFeedback** in a **Button** is not "Eye Candy" @steida. 
I'd love to use the default Ripple effect on my Android apps for these reasons:

1. Android Users are used to the ripple effect. It's feels natural and original for anyone using an Android phone for more than 1 week. I expect to see a ripple whenever I click on a button on the Android platform. Breaking this pattern is just not right.

2. The **TouchableOpacity** is heavier since it's rendered/calculated in the JS code. I'm using NativeBase's **Button** in one of my apps and it works fine for iOS, but the opacity animation feels sluggish on Android.

3. The Ripple effect is shipped with Android as an **background** that you can use in whatever component you want (as long as it extends **View**). **It is ran in the native side.**

**Comment by sanketsahusoft** [comment]
Closing because most of the things discussed here has been achieved in 2.0

**Comment by stonecold123** [comment]
@sanketsahusoft 
Is popup menu part of the future components?

**Comment by sanketsahusoft** [comment]
@stonecold123 We are working on the following items this week.

- [ ] ActionSheet (Material & iOS Native)
- [x] Toast (Pushed and Merged)
- [ ] Prompt (RN doesn't support Prompt by default on Android)
- [ ] Alert & Confirm (If it doesn't add anything we will just export RN's implementation)

**Comment by franzejr** [comment]
Hey @sanketsahusoft , i think the popup they are referring are:

![image](https://user-images.githubusercontent.com/868917/39593303-c2c5a15e-4edf-11e8-8566-6ffcf43394dd.png)

:)

**Comment by vibhavagarwal5** [comment]
Can we have a slider pls? Similar to [this](https://github.com/jeanregisser/react-native-slider)

**Comment by devarashetty** [comment]
I am currently checking with `Tabs` Component.I am trying to make sure the scroll will make sure to jump to next tab instead of multiple tabs. I am attaching the a video screen where I tried to show the usage .Let me know if you guys think its worth a try and can be thought of adding the feature to tabs.

**Comment by sleepwalkerfx** [comment]
Is pagination in list views supported yet?

**Comment by madroneropaulo** [comment]
Any news on the popup? @franzejr mentioned it before. Thx!
